services:
  - type: web
    name: fake-data-api
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
