services:
  - type: web
    name: fake-data-api
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rackup -p $PORT -o 0.0.0.0
    envVars:
      - key: RACK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
